name: Rollback Render Deploy

on:
  workflow_call:
    inputs:
      render_service_id:
        description: 'Render Service ID'
        required: true
        type: string
    secrets:
      render_api_key:
        description: 'Render API Key'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    name: Rollback to last successful deploy
    
    steps:
      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Find last successful deploy and trigger rollback
        env:
          RENDER_API_KEY: ${{ secrets.render_api_key }}
          RENDER_SERVICE_ID: ${{ inputs.render_service_id }}
        run: |
          echo "Finding last successful deploy for service $RENDER_SERVICE_ID..."

          # 1. Listar deploys y encontrar el commit ID del último deploy 'live'
          LAST_SUCCESSFUL_COMMIT_ID=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
                                           -H "Accept: application/json" \
                                           "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys?limit=20" | \
                                      jq -r '.[] | select(.status == "live") | .commit.id' | head -n 1)

          if [ -z "$LAST_SUCCESSFUL_COMMIT_ID" ]; then
            echo "::error::No successful deploy found to roll back to."
            exit 1
          fi

          echo "Found last successful commit: $LAST_SUCCESSFUL_COMMIT_ID"
          echo "Triggering rollback..."

          # 2. Crear un nuevo deploy usando ese commit ID exitoso
          ROLLBACK_RESPONSE=$(curl -s -X POST -H "Authorization: Bearer $RENDER_API_KEY" \
                                   -H "Accept: application/json" \
                                   -H "Content-Type: application/json" \
                                   -d "{\"commitId\": \"$LAST_SUCCESSFUL_COMMIT_ID\", \"clearCache\": false}" \
                                   "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys")

          echo "Rollback triggered. Response:"
          echo $ROLLBACK_RESPONSE | jq
          
          DEPLOY_ID=$(echo $ROLLBACK_RESPONSE | jq -r '.id')
          echo "Rollback deploy ID: $DEPLOY_ID. Monitor its progress in Render."
